### PR TITLE
Bump to support PSC 0.9

### PR DESCRIPTION
**Pull request by chexxor**
Looking for opinions on these changes. I'm new to PS. I haven't used this as-is yet, but it successfully builds.

Bump dependency versions. Require mustache in the FFI JS to support running `pulp test`.

### CODE REVIEW

**Comment by svisser** [comment]
@chexxor Thanks for making these changes! It's been a while since I used PureScript but I'll take a closer look soon and merge it in so that the code can be used with a more modern PureScript version.

**Comment by chexxor** [comment]
No problem. This PR doesn't even compile, I believe, as I think I used the wrong comment syntax.

I'm still iterating on this - I'm getting rid of the StrMap and replacing with native PS records. I'm adding some tests, too.

We can discuss making me the maintainer instead of you, if you'd like. I'm planning to use this in a project I'm starting.

**Comment by svisser** [comment]
@chexxor hey there, sorry for not getting back to you. Are you perhaps still interested in becoming the maintainer of this project? I do think it's better if an active user of this code also maintains the project.

If not, that's okay too - in that case I'll refresh my PureScript knowledge, merge in your changes and produce a new package.

**Comment by chexxor** [comment]
I'm not using this package myself, but I don't mind maintaining it. I'm relatively active with PureScript right now, and I'm planning to continue for several months.

**Comment by svisser** [comment]
@chexxor the project now supports the latest compiler as a result of this pull request: https://github.com/svisser/purescript-mustache/pull/3.

However, looking at the changes in this pull request, the project still uses `Data.StrMap`. I'm not familiar with `Record` but would you say it's worthwhile to convert this project over to use that instead?

**Comment by chexxor** [comment]
Thanks for poking me about this again! I'm quite a bit more experienced with PS now, so I can see that my MR got some things wrong, and I can see a more type-safe way to do this FFI.

If this project switches to Record, there can be much better type-checking. For example:

``` purescript
newtype Template i = Template String
type View i = Record i
foreign import data MUSTACHE :: Effect
-- This function type-checks that the Template and its ViewModel have the same properties.
foreign import render :: forall i eff. Template i -> View i -> Partials -> Eff (mustache :: MUSTACHE | eff) String

-- Owner of this function needs to accurately represent the parameters of the template.
-- Be responsible!
emailTemplate :: Template ( name :: String, amount :: Int )
emailTemplate = 
  """
  Hello {{name}}, you have won ${{amount}}!
  """

-- A model is just a Record.
emailModel :: View ( name :: String, amount :: Int )
emailModel = { name: "John", amount: 1000000 }

main = do
  -- emailTemplate and emailModel must have the same keys
  formattedTemplate <- render emailTemplate emailModel mempty
```

gtg for now.

**Comment by chexxor** [comment]
LMK if you're interested in my updating my PR to make `render` more safe like this.

**Comment by chexxor** [comment]
Closing in favor of https://github.com/svisser/purescript-mustache/pull/4
Thanks!

**Pull request closed without merging**
